version: '3.4'
services:
  deploy:
    build: .
    image: public.ecr.aws/dnxsolutions/ecs-deploy:latest
    env_file:
      - .env
    volumes:
      - ./templates/task-definition.tpl-default.json:/work/task-definition.tpl.json

  cutover:
    build: .
    image: public.ecr.aws/dnxsolutions/ecs-deploy:latest
    env_file:
      - .env
    command: /work/deploy-cutover.py

  run-task:
    build: .
    image: public.ecr.aws/dnxsolutions/ecs-deploy:latest
    env_file:
      - .env
    command: /work/run-task.py
    volumes:
      - ./templates/task-definition.tpl-default.json:/work/task-definition.tpl.json

  worker-deploy:
    build: .
    image: public.ecr.aws/dnxsolutions/ecs-deploy:latest
    env_file:
      - .env
    command: /work/worker-deploy.py
    volumes:
      - ./templates/task-definition.tpl-default.json:/work/task-definition.tpl.json

  ecr-scan:
    build: .
    image: public.ecr.aws/dnxsolutions/ecs-deploy:latest
    env_file:
      - .env
    command: /work/ecr-enhanced-scanning.py
    volumes:
      - ./templates/task-definition.tpl-default.json:/work/task-definition.tpl.json
