name: Security

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Build the container image
        run: docker build . --file Dockerfile --tag dnxsolutions/ecs-deploy:latest
      - name: Scan image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: "dnxsolutions/ecs-deploy:latest"
          fail-build: false
          severity-cutoff: critical
      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
      - name: Upload Anchore Scan Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}